import {
  Employee,
  Contract,
  WorkingSchedule,
  AttendanceRecord,
  TimeOffType,
  Allocation,
  TimeOffRequest,
  SalaryStructure,
  SalaryRule,
  Payrun,
  Payslip,
  Department,
  JobPosition,
  User,
} from '../types';

// Frontend-only reference lists for dropdowns - department/jobPosition are
// plain free-text fields on Employee/Contract, not real backend entities.
export const initialDepartments: Department[] = [
  { id: 1, name: 'Engineering', code: 'ENG', managerName: 'Priya Nair', employeeCount: 3 },
  { id: 2, name: 'Human Resources', code: 'HR', managerName: 'Ananya Iyer', employeeCount: 2 },
  { id: 3, name: 'Finance & Payroll', code: 'FIN', managerName: 'Vikram Rao', employeeCount: 2 },
  { id: 4, name: 'Sales', code: 'SLS', managerName: 'Ananya Iyer', employeeCount: 1 },
];

export const initialJobPositions: JobPosition[] = [
  { id: 1, title: 'Software Engineer', departmentName: 'Engineering' },
  { id: 2, title: 'Engineering Manager', departmentName: 'Engineering' },
  { id: 3, title: 'HR Manager', departmentName: 'Human Resources' },
  { id: 4, title: 'HR Executive', departmentName: 'Human Resources' },
  { id: 5, title: 'Payroll Manager', departmentName: 'Finance & Payroll' },
  { id: 6, title: 'Payroll Administrator', departmentName: 'Finance & Payroll' },
  { id: 7, title: 'Sales Executive', departmentName: 'Sales' },
];

export const initialSchedules: WorkingSchedule[] = [
  {
    id: '1',
    name: 'Standard 9-to-6 (Mon-Fri)',
    isActive: true,
    weeklyHours: 40,
    lines: [
      { dayOfWeek: 0, isWorkingDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { dayOfWeek: 1, isWorkingDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { dayOfWeek: 2, isWorkingDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { dayOfWeek: 3, isWorkingDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { dayOfWeek: 4, isWorkingDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { dayOfWeek: 5, isWorkingDay: false, startTime: null, endTime: null, breakMinutes: 0 },
      { dayOfWeek: 6, isWorkingDay: false, startTime: null, endTime: null, breakMinutes: 0 },
    ],
  },
  {
    id: '2',
    name: 'Part-Time 9-to-1 (Mon-Fri)',
    isActive: true,
    weeklyHours: 20,
    lines: [
      { dayOfWeek: 0, isWorkingDay: true, startTime: '09:00', endTime: '13:00', breakMinutes: 0 },
      { dayOfWeek: 1, isWorkingDay: true, startTime: '09:00', endTime: '13:00', breakMinutes: 0 },
      { dayOfWeek: 2, isWorkingDay: true, startTime: '09:00', endTime: '13:00', breakMinutes: 0 },
      { dayOfWeek: 3, isWorkingDay: true, startTime: '09:00', endTime: '13:00', breakMinutes: 0 },
      { dayOfWeek: 4, isWorkingDay: true, startTime: '09:00', endTime: '13:00', breakMinutes: 0 },
      { dayOfWeek: 5, isWorkingDay: false, startTime: null, endTime: null, breakMinutes: 0 },
      { dayOfWeek: 6, isWorkingDay: false, startTime: null, endTime: null, breakMinutes: 0 },
    ],
  },
];

export const initialEmployees: Employee[] = [
  {
    id: '1',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@peoplepay360.demo',
    phone: '+91 98765 43210',
    department: 'Human Resources',
    jobPosition: 'HR Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'hr_manager',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-001-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '2',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@peoplepay360.demo',
    phone: '+91 98765 43211',
    department: 'Engineering',
    jobPosition: 'Software Engineer',
    managerId: '3',
    managerName: 'Priya Nair',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'employee',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-002-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '3',
    name: 'Priya Nair',
    email: 'priya.nair@peoplepay360.demo',
    phone: '+91 98765 43212',
    department: 'Engineering',
    jobPosition: 'Engineering Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'employee',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-003-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '4',
    name: 'Vikram Rao',
    email: 'vikram.rao@peoplepay360.demo',
    phone: '+91 98765 43213',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'hr_payroll_manager',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-004-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '5',
    name: 'Sneha Deshmukh',
    email: 'sneha.deshmukh@peoplepay360.demo',
    phone: '+91 98765 43214',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Administrator',
    managerId: '4',
    managerName: 'Vikram Rao',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'hr_payroll_user',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-005-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '6',
    name: 'Arjun Menon',
    email: 'arjun.menon@peoplepay360.demo',
    phone: '+91 98765 43215',
    department: 'Sales',
    jobPosition: 'Sales Executive',
    managerId: '1',
    managerName: 'Ananya Iyer',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'employee',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-006-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '7',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@peoplepay360.demo',
    phone: '+91 98765 43216',
    department: 'Human Resources',
    jobPosition: 'HR Executive',
    managerId: '1',
    managerName: 'Ananya Iyer',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'employee',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-007-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
  {
    id: '8',
    name: 'Ishaan Kapoor',
    email: 'ishaan.kapoor@peoplepay360.demo',
    phone: '+91 98765 43217',
    department: 'Engineering',
    jobPosition: 'Software Engineer',
    managerId: '3',
    managerName: 'Priya Nair',
    workingScheduleId: '2',
    workingScheduleName: 'Part-Time 9-to-1 (Mon-Fri)',
    roleName: 'employee',
    employmentStatus: 'active',
    // Missing bank details triggers demo payroll warning!
    bankAccountNumber: undefined,
    bankName: undefined,
    bankIfsc: undefined,
  },
  {
    id: '9',
    name: 'Admin User',
    email: 'admin@peoplepay360.demo',
    phone: '+91 99999 99999',
    department: 'Human Resources',
    jobPosition: 'HR Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    roleName: 'admin',
    employmentStatus: 'active',
    bankAccountNumber: 'EMP-009-BANKACC-0001',
    bankName: 'National Trust Bank',
    bankIfsc: 'NTBK0001234',
  },
];

export const initialSalaryStructures: SalaryStructure[] = [
  {
    id: '1',
    name: 'Regular Salary',
    isActive: true,
    rulesCount: 8,
  },
];

export const initialSalaryRules: SalaryRule[] = [
  {
    id: '1',
    salaryStructureId: '1',
    name: 'Basic Salary',
    code: 'BASIC',
    category: 'basic',
    sequence: 10,
    computationType: 'percentage',
    percentageBase: 'WAGE',
    percentage: 50.0,
    isActive: true,
  },
  {
    id: '2',
    salaryStructureId: '1',
    name: 'House Rent Allowance (HRA)',
    code: 'HRA',
    category: 'allowance',
    sequence: 20,
    computationType: 'percentage',
    percentageBase: 'BASIC',
    percentage: 40.0,
    isActive: true,
  },
  {
    id: '3',
    salaryStructureId: '1',
    name: 'Transport Allowance',
    code: 'TRANS',
    category: 'allowance',
    sequence: 30,
    computationType: 'fixed',
    amount: 3000,
    isActive: true,
  },
  {
    id: '4',
    salaryStructureId: '1',
    name: 'Gross Salary',
    code: 'GROSS',
    category: 'gross',
    sequence: 40,
    computationType: 'formula',
    formula: 'BASIC + HRA + TRANS',
    isActive: true,
  },
  {
    id: '5',
    salaryStructureId: '1',
    name: 'Provident Fund (PF)',
    code: 'PF',
    category: 'deduction',
    sequence: 50,
    computationType: 'percentage',
    percentageBase: 'BASIC',
    percentage: 12.0,
    isActive: true,
  },
  {
    id: '6',
    salaryStructureId: '1',
    name: 'Professional Tax (PT)',
    code: 'PT',
    category: 'deduction',
    sequence: 60,
    computationType: 'fixed',
    amount: 200,
    isActive: true,
  },
  {
    id: '7',
    salaryStructureId: '1',
    name: 'Tax Deducted at Source (TDS)',
    code: 'TDS',
    category: 'deduction',
    sequence: 70,
    computationType: 'percentage',
    percentageBase: 'GROSS',
    percentage: 10.0,
    isActive: true,
  },
  {
    id: '8',
    salaryStructureId: '1',
    name: 'Net Salary',
    code: 'NET',
    category: 'net',
    sequence: 80,
    computationType: 'formula',
    formula: 'GROSS - PF - PT - TDS',
    isActive: true,
  },
];

export const initialContracts: Contract[] = [
  {
    id: '1',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    dateStart: '2025-01-01',
    dateEnd: '2025-12-31',
    wage: 66666.67,
    department: 'Engineering',
    jobPosition: 'Software Engineer',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'expired',
  },
  {
    id: '2',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    dateStart: '2026-01-01',
    dateEnd: null, // open-ended
    wage: 100000,
    department: 'Engineering',
    jobPosition: 'Software Engineer',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '3',
    employeeId: '1',
    employeeName: 'Ananya Iyer',
    dateStart: '2022-03-01',
    dateEnd: null,
    wage: 75000,
    department: 'Human Resources',
    jobPosition: 'HR Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '4',
    employeeId: '3',
    employeeName: 'Priya Nair',
    dateStart: '2021-06-15',
    dateEnd: null,
    wage: 125000,
    department: 'Engineering',
    jobPosition: 'Engineering Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '5',
    employeeId: '4',
    employeeName: 'Vikram Rao',
    dateStart: '2020-11-10',
    dateEnd: null,
    wage: 116666.67,
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Manager',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '6',
    employeeId: '5',
    employeeName: 'Sneha Deshmukh',
    dateStart: '2023-02-20',
    dateEnd: null,
    wage: 58333.33,
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Administrator',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '7',
    employeeId: '6',
    employeeName: 'Arjun Menon',
    dateStart: '2024-07-01',
    dateEnd: null,
    wage: 50000,
    department: 'Sales',
    jobPosition: 'Sales Executive',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '8',
    employeeId: '7',
    employeeName: 'Kavya Reddy',
    dateStart: '2024-09-05',
    dateEnd: null,
    wage: 45833.33,
    department: 'Human Resources',
    jobPosition: 'HR Executive',
    workingScheduleId: '1',
    workingScheduleName: 'Standard 9-to-6 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
  {
    id: '9',
    employeeId: '8',
    employeeName: 'Ishaan Kapoor',
    dateStart: '2026-01-15',
    dateEnd: '2026-07-14',
    wage: 15000,
    department: 'Engineering',
    jobPosition: 'Software Engineer',
    workingScheduleId: '2',
    workingScheduleName: 'Part-Time 9-to-1 (Mon-Fri)',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    status: 'active',
  },
];

export const initialAttendance: AttendanceRecord[] = [
  {
    id: '1',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    departmentName: 'Engineering',
    checkIn: '2026-09-01T09:05:00Z',
    checkOut: '2026-09-01T18:10:00Z',
    workedHours: 8.08,
    status: 'present',
    isManual: false,
  },
  {
    id: '2',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    departmentName: 'Engineering',
    checkIn: '2026-09-02T09:45:00Z',
    checkOut: '2026-09-02T18:00:00Z',
    workedHours: 7.25,
    status: 'late',
    isManual: false,
    note: 'Traffic delay on highway',
  },
  {
    id: '3',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    departmentName: 'Engineering',
    checkIn: '2026-09-03T09:00:00Z',
    checkOut: '2026-09-03T19:30:00Z',
    workedHours: 9.50,
    status: 'overtime',
    isManual: false,
  },
  {
    id: '4',
    employeeId: '1',
    employeeName: 'Ananya Iyer',
    departmentName: 'Human Resources',
    checkIn: '2026-09-03T08:55:00Z',
    checkOut: '2026-09-03T18:05:00Z',
    workedHours: 8.16,
    status: 'present',
    isManual: false,
  },
  {
    id: '5',
    employeeId: '8',
    employeeName: 'Ishaan Kapoor',
    departmentName: 'Engineering',
    checkIn: '2026-09-03T09:10:00Z',
    checkOut: null, // missing check-out exception!
    workedHours: null,
    status: 'absent',
    isManual: false,
    note: 'Missing punch out timestamp',
  },
  {
    id: '6',
    employeeId: '3',
    employeeName: 'Priya Nair',
    departmentName: 'Engineering',
    checkIn: '2026-09-04T09:00:00Z',
    checkOut: '2026-09-04T18:00:00Z',
    workedHours: 8.00,
    status: 'present',
    isManual: true,
    note: 'Manual swipe fix requested via email',
  },
];

export const initialTimeOffTypes: TimeOffType[] = [
  { id: '1', name: 'Paid Time Off', unit: 'days', requiresAllocation: true, approvalRequired: true, isActive: true },
  { id: '2', name: 'Sick Leave', unit: 'days', requiresAllocation: true, approvalRequired: true, isActive: true },
  { id: '3', name: 'Casual Leave', unit: 'days', requiresAllocation: true, approvalRequired: true, isActive: true },
  { id: '4', name: 'Unpaid Leave', unit: 'days', requiresAllocation: false, approvalRequired: true, isActive: true },
];

export const initialAllocations: Allocation[] = [
  {
    id: '1',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    timeOffTypeId: '1',
    timeOffTypeName: 'Paid Time Off',
    numberOfDays: 20,
    taken: 3,
    remaining: 17, // Mirrors README / seed.sql example!
    dateFrom: '2026-01-01',
    dateTo: '2026-12-31',
    status: 'approved',
  },
  {
    id: '2',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    timeOffTypeId: '2',
    timeOffTypeName: 'Sick Leave',
    numberOfDays: 10,
    taken: 1,
    remaining: 9,
    dateFrom: '2026-01-01',
    dateTo: '2026-12-31',
    status: 'approved',
  },
  {
    id: '3',
    employeeId: '1',
    employeeName: 'Ananya Iyer',
    timeOffTypeId: '1',
    timeOffTypeName: 'Paid Time Off',
    numberOfDays: 24,
    taken: 4,
    remaining: 20,
    dateFrom: '2026-01-01',
    dateTo: '2026-12-31',
    status: 'approved',
  },
  {
    id: '4',
    employeeId: '3',
    employeeName: 'Priya Nair',
    timeOffTypeId: '1',
    timeOffTypeName: 'Paid Time Off',
    numberOfDays: 24,
    taken: 2,
    remaining: 22,
    dateFrom: '2026-01-01',
    dateTo: '2026-12-31',
    status: 'approved',
  },
];

export const initialTimeOffRequests: TimeOffRequest[] = [
  {
    id: '1',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    departmentName: 'Engineering',
    timeOffTypeId: '1',
    timeOffTypeName: 'Paid Time Off',
    allocationId: '1',
    dateFrom: '2026-08-10',
    dateTo: '2026-08-12',
    duration: 3,
    status: 'approved',
    note: 'Family visit out of town',
  },
  {
    id: '2',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    departmentName: 'Engineering',
    timeOffTypeId: '2',
    timeOffTypeName: 'Sick Leave',
    allocationId: '2',
    dateFrom: '2026-08-25',
    dateTo: '2026-08-25',
    duration: 1,
    status: 'approved',
    note: 'Viral fever consultation',
  },
  {
    id: '3',
    employeeId: '6',
    employeeName: 'Arjun Menon',
    departmentName: 'Sales',
    timeOffTypeId: '1',
    timeOffTypeName: 'Paid Time Off',
    dateFrom: '2026-09-15',
    dateTo: '2026-09-18',
    duration: 4,
    status: 'confirmed',
    note: 'Annual personal leave',
  },
  {
    id: '4',
    employeeId: '7',
    employeeName: 'Kavya Reddy',
    departmentName: 'Human Resources',
    timeOffTypeId: '3',
    timeOffTypeName: 'Casual Leave',
    dateFrom: '2026-09-20',
    dateTo: '2026-09-21',
    duration: 2,
    status: 'confirmed',
    note: 'Attending college convocation ceremony',
  },
];

export const initialPayruns: Payrun[] = [
  {
    id: '1',
    name: 'August 2026 Regular Payrun',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    status: 'paid',
    employeeCount: 8,
    totalGross: 815000,
    totalDeductions: 135000,
    totalNet: 680000,
    warningsCount: 0,
  },
  {
    id: '2',
    name: 'September 2026 Monthly Payrun',
    salaryStructureId: '1',
    salaryStructureName: 'Regular Salary',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    status: 'draft',
    employeeCount: 8,
    totalGross: 0,
    totalDeductions: 0,
    totalNet: 0,
    warningsCount: 1,
    createdAt: '2026-09-01T09:00:00Z',
  },
];

export const initialPayslips: Payslip[] = [
  {
    id: '1',
    payrunId: '1',
    payrunName: 'August 2026 Regular Payrun',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    departmentName: 'Engineering',
    jobPositionTitle: 'Software Engineer',
    bankAccountNumber: 'EMP-002-BANKACC-0001',
    bankName: 'National Trust Bank',
    contractId: '2',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    workedDays: 22,
    grossSalary: 73000, // Monthly wage 100,000 -> Basic=50,000, HRA=20,000, Trans=3000 -> Gross=73,000
    netSalary: 59500, // Deductions: PF=6,000, PT=200, TDS=7,300 -> 13,500; 73,000 - 13,500 = 59,500
    status: 'paid',
    warnings: [],
    lines: [
      { id: '1', payslipId: '1', code: 'BASIC', name: 'Basic Salary', category: 'basic', sequence: 10, amount: 50000 },
      { id: '2', payslipId: '1', code: 'HRA', name: 'House Rent Allowance (HRA)', category: 'allowance', sequence: 20, amount: 20000 },
      { id: '3', payslipId: '1', code: 'TRANS', name: 'Transport Allowance', category: 'allowance', sequence: 30, amount: 3000 },
      { id: '4', payslipId: '1', code: 'GROSS', name: 'Gross Salary', category: 'gross', sequence: 40, amount: 73000 },
      { id: '5', payslipId: '1', code: 'PF', name: 'Provident Fund (PF)', category: 'deduction', sequence: 50, amount: 6000 },
      { id: '6', payslipId: '1', code: 'PT', name: 'Professional Tax (PT)', category: 'deduction', sequence: 60, amount: 200 },
      { id: '7', payslipId: '1', code: 'TDS', name: 'Tax Deducted at Source (TDS)', category: 'deduction', sequence: 70, amount: 7300 },
      { id: '8', payslipId: '1', code: 'NET', name: 'Net Salary', category: 'net', sequence: 80, amount: 59500 },
    ],
  },
  {
    id: '2',
    payrunId: '1',
    payrunName: 'August 2026 Regular Payrun',
    employeeId: '1',
    employeeName: 'Ananya Iyer',
    departmentName: 'Human Resources',
    jobPositionTitle: 'HR Manager',
    bankAccountNumber: 'EMP-001-BANKACC-0001',
    bankName: 'National Trust Bank',
    contractId: '3',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    workedDays: 22,
    grossSalary: 84666,
    netSalary: 69000,
    status: 'paid',
    warnings: [],
  },
];

export const demoUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    role: 'admin',
    employeeId: '9',
    employeeName: 'Admin User',
    email: 'admin@peoplepay360.demo',
    isActive: true,
  },
  {
    id: '2',
    username: 'vikram.rao',
    role: 'hr_payroll_manager',
    employeeId: '4',
    employeeName: 'Vikram Rao',
    email: 'vikram.rao@peoplepay360.demo',
    isActive: true,
  },
  {
    id: '3',
    username: 'sneha.deshmukh',
    role: 'hr_payroll_user',
    employeeId: '5',
    employeeName: 'Sneha Deshmukh',
    email: 'sneha.deshmukh@peoplepay360.demo',
    isActive: true,
  },
  {
    id: '4',
    username: 'ananya.iyer',
    role: 'hr_manager',
    employeeId: '1',
    employeeName: 'Ananya Iyer',
    email: 'ananya.iyer@peoplepay360.demo',
    isActive: true,
  },
  {
    id: '5',
    username: 'rahul.sharma',
    role: 'employee',
    employeeId: '2',
    employeeName: 'Rahul Sharma',
    email: 'rahul.sharma@peoplepay360.demo',
    isActive: true,
  },
];
